using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace NetworkExample.Kernel
{
    /// <summary>
    /// A small strict JSON reader, used for skeleton manifests.
    /// </summary>
    /// <remarks>
    /// JsonUtility is not used here for two reasons: it cannot express the
    /// manifest's <c>[x, y, z]</c> rest-pose arrays as anything but a wrapper
    /// type per field, and it only exists inside Unity, which would put the
    /// parser out of reach of headless tests. The input is machine-generated by
    /// //tools:ozz_skeleton_manifest, so this only has to read well-formed JSON
    /// -- but it rejects malformed input rather than guessing, because a
    /// silently half-parsed skeleton would surface as a mis-posed rig.
    /// </remarks>
    internal static class KernelJson
    {
        internal enum ValueKind
        {
            Null,
            Boolean,
            Number,
            String,
            Array,
            Object,
        }

        internal struct Value
        {
            public ValueKind Kind;
            public double Number;
            public bool Boolean;
            public string String;
            public List<Value> Array;
            public Dictionary<string, Value> Object;

            public bool TryGet(string key, out Value value)
            {
                if (Kind != ValueKind.Object || Object == null)
                {
                    value = default;
                    return false;
                }
                return Object.TryGetValue(key, out value);
            }

            public bool TryGetNumber(string key, out double number)
            {
                number = 0.0;
                if (!TryGet(key, out Value value) || value.Kind != ValueKind.Number)
                {
                    return false;
                }
                number = value.Number;
                return true;
            }

            public bool TryGetString(string key, out string text)
            {
                text = null;
                if (!TryGet(key, out Value value) || value.Kind != ValueKind.String)
                {
                    return false;
                }
                text = value.String;
                return true;
            }

            public bool TryGetArray(string key, out List<Value> array)
            {
                array = null;
                if (!TryGet(key, out Value value) || value.Kind != ValueKind.Array)
                {
                    return false;
                }
                array = value.Array;
                return true;
            }
        }

        internal static bool TryParse(string text, out Value value, out string error)
        {
            value = default;
            error = null;
            if (text == null)
            {
                error = "JSON input is null.";
                return false;
            }
            int position = 0;
            try
            {
                value = ParseValue(text, ref position);
                SkipWhitespace(text, ref position);
                if (position != text.Length)
                {
                    error = $"unexpected trailing content at offset {position}.";
                    return false;
                }
                return true;
            }
            catch (FormatException exception)
            {
                error = exception.Message;
                return false;
            }
        }

        private static Value ParseValue(string text, ref int position)
        {
            SkipWhitespace(text, ref position);
            if (position >= text.Length)
            {
                throw new FormatException("unexpected end of JSON input.");
            }
            char current = text[position];
            switch (current)
            {
            case '{': return ParseObject(text, ref position);
            case '[': return ParseArray(text, ref position);
            case '"':
                return new Value
                {
                    Kind = ValueKind.String,
                    String = ParseString(text, ref position),
                };
            case 't':
                Expect(text, ref position, "true");
                return new Value { Kind = ValueKind.Boolean, Boolean = true };
            case 'f':
                Expect(text, ref position, "false");
                return new Value { Kind = ValueKind.Boolean, Boolean = false };
            case 'n':
                Expect(text, ref position, "null");
                return new Value { Kind = ValueKind.Null };
            default:
                return new Value
                {
                    Kind = ValueKind.Number,
                    Number = ParseNumber(text, ref position),
                };
            }
        }

        private static Value ParseObject(string text, ref int position)
        {
            var members = new Dictionary<string, Value>();
            ++position;  // '{'
            SkipWhitespace(text, ref position);
            if (position < text.Length && text[position] == '}')
            {
                ++position;
                return new Value { Kind = ValueKind.Object, Object = members };
            }
            while (true)
            {
                SkipWhitespace(text, ref position);
                string key = ParseString(text, ref position);
                SkipWhitespace(text, ref position);
                if (position >= text.Length || text[position] != ':')
                {
                    throw new FormatException($"expected ':' at offset {position}.");
                }
                ++position;
                members[key] = ParseValue(text, ref position);
                SkipWhitespace(text, ref position);
                if (position >= text.Length)
                {
                    throw new FormatException("unterminated object.");
                }
                if (text[position] == ',')
                {
                    ++position;
                    continue;
                }
                if (text[position] == '}')
                {
                    ++position;
                    return new Value { Kind = ValueKind.Object, Object = members };
                }
                throw new FormatException($"expected ',' or '}}' at offset {position}.");
            }
        }

        private static Value ParseArray(string text, ref int position)
        {
            var items = new List<Value>();
            ++position;  // '['
            SkipWhitespace(text, ref position);
            if (position < text.Length && text[position] == ']')
            {
                ++position;
                return new Value { Kind = ValueKind.Array, Array = items };
            }
            while (true)
            {
                items.Add(ParseValue(text, ref position));
                SkipWhitespace(text, ref position);
                if (position >= text.Length)
                {
                    throw new FormatException("unterminated array.");
                }
                if (text[position] == ',')
                {
                    ++position;
                    continue;
                }
                if (text[position] == ']')
                {
                    ++position;
                    return new Value { Kind = ValueKind.Array, Array = items };
                }
                throw new FormatException($"expected ',' or ']' at offset {position}.");
            }
        }

        private static string ParseString(string text, ref int position)
        {
            if (position >= text.Length || text[position] != '"')
            {
                throw new FormatException($"expected a string at offset {position}.");
            }
            ++position;
            var builder = new StringBuilder();
            while (true)
            {
                if (position >= text.Length)
                {
                    throw new FormatException("unterminated string.");
                }
                char current = text[position++];
                if (current == '"')
                {
                    return builder.ToString();
                }
                if (current != '\\')
                {
                    builder.Append(current);
                    continue;
                }
                if (position >= text.Length)
                {
                    throw new FormatException("unterminated escape sequence.");
                }
                char escape = text[position++];
                switch (escape)
                {
                case '"': builder.Append('"'); break;
                case '\\': builder.Append('\\'); break;
                case '/': builder.Append('/'); break;
                case 'b': builder.Append('\b'); break;
                case 'f': builder.Append('\f'); break;
                case 'n': builder.Append('\n'); break;
                case 'r': builder.Append('\r'); break;
                case 't': builder.Append('\t'); break;
                case 'u':
                    if (position + 4 > text.Length ||
                        !ushort.TryParse(
                            text.Substring(position, 4),
                            NumberStyles.HexNumber,
                            CultureInfo.InvariantCulture,
                            out ushort code))
                    {
                        throw new FormatException(
                            $"invalid \\u escape at offset {position}.");
                    }
                    builder.Append((char)code);
                    position += 4;
                    break;
                default:
                    throw new FormatException(
                        $"invalid escape '\\{escape}' at offset {position - 1}.");
                }
            }
        }

        private static double ParseNumber(string text, ref int position)
        {
            int start = position;
            if (position < text.Length && (text[position] == '-' || text[position] == '+'))
            {
                ++position;
            }
            while (position < text.Length)
            {
                char current = text[position];
                if ((current >= '0' && current <= '9') || current == '.' ||
                    current == 'e' || current == 'E' || current == '-' || current == '+')
                {
                    ++position;
                    continue;
                }
                break;
            }
            if (position == start ||
                !double.TryParse(
                    text.Substring(start, position - start),
                    NumberStyles.Float,
                    CultureInfo.InvariantCulture,
                    out double value))
            {
                throw new FormatException($"invalid number at offset {start}.");
            }
            return value;
        }

        private static void Expect(string text, ref int position, string literal)
        {
            if (position + literal.Length > text.Length ||
                string.CompareOrdinal(text, position, literal, 0, literal.Length) != 0)
            {
                throw new FormatException(
                    $"expected '{literal}' at offset {position}.");
            }
            position += literal.Length;
        }

        private static void SkipWhitespace(string text, ref int position)
        {
            while (position < text.Length)
            {
                char current = text[position];
                if (current == ' ' || current == '\t' || current == '\n' || current == '\r')
                {
                    ++position;
                    continue;
                }
                break;
            }
        }
    }
}
