licenses(["notice"])

cc_test(
    name = "network_packets_test",
    srcs = ["network_packets_test.cc"],
    deps = ["//engine/src/protocol:protocol"],
)

cc_test(
    name = "status_effect_packet_test",
    srcs = ["status_effect_packet_test.cc"],
    deps = ["//engine/src/protocol:protocol"],
)

cc_test(
    name = "packet_header_test",
    srcs = ["packet_header_test.cc"],
    deps = ["//engine/src/protocol:protocol"],
)

cc_test(
    name = "session_packets_test",
    srcs = ["session_packets_test.cc"],
    deps = ["//engine/src/protocol:protocol"],
)

cc_test(
    name = "sha256_test",
    srcs = ["sha256_test.cc"],
    deps = ["//engine/src/protocol:protocol"],
)

cc_test(
    name = "beam_roundtrip_test",
    srcs = ["beam_roundtrip_test.cc"],
    deps = ["//engine/src/protocol:protocol", "//engine/src/sync:sync"],
)
