licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "physics",
    srcs = ["src/physics_world.cc"],
    hdrs = [
        "public/collision_types.h",
        "public/physics_world.h",
    ],
    includes = [".."],
    deps = [
        "@glm//:glm",
        "@jolt_physics//:jolt",
    ],
)
