#!/usr/bin/env python3
"""Generates the obstructed_field test terrain.

undulating.obj answers "does rolling ground block a straight route" and says
yes. It cannot answer "how much of an authored rectangle can a patrol actually
spawn in", because it is a heightfield with no holes: every XZ position has
walkable ground under it, so the coverage metric reads 100% by construction.

This terrain is flat -- height is deliberately not a variable here -- and blocks
movement the way a built level does, with pits and standing walls:

  * pits are quads left out of the ground grid, so the ground is genuinely
    missing rather than steep.
  * walls are 1 m thick and 5 m tall. The thickness is the load-bearing number:
    Recast erodes walkable area by agent_radius (0.6 m), so a 1 m wall top
    erodes away completely and leaves no unreachable rooftop island to confuse
    the connectivity measurement. Anything thicker would need its roof reasoned
    about separately.
  * one sealed courtyard, which is the control for the connectivity metric: its
    interior is walkable and has no entrance, so a measurement that reports
    100% connected is not measuring anything.

Regenerate with:
  python3 tools/make_obstructed_field_obj.py \
      game_server/tests/test_mesh_assets/raw/obstructed_field.obj
"""

import sys

HALF_EXTENT = 50.0
CELL = 2.5
WALL_HEIGHT = 5.0

# (x0, z0, x1, z1) rectangles where the ground grid has no quads.
PITS = [
    (-40.0, -40.0, -27.5, -30.0),
    (17.5, -42.5, 27.5, -27.5),
    (-25.0, 20.0, -7.5, 27.5),
    (30.0, 27.5, 40.0, 37.5),
    (-7.5, -7.5, 7.5, 7.5),
]

# (x0, z0, x1, z1) footprints of 1 m thick walls. The first four partition the
# field into a zigzag: crossing it end to end has to weave around them.
WALLS = [
    (-50.0, -18.0, 12.5, -17.0),
    (-12.5, 17.0, 50.0, 18.0),
    (4.5, -50.0, 5.5, -32.5),
    (-15.5, 30.0, -14.5, 50.0),
    # Sealed courtyard, outer extent x[-45, -30] z[30, 45].
    (-45.0, 30.0, -30.0, 31.0),
    (-45.0, 44.0, -30.0, 45.0),
    (-45.0, 30.0, -44.0, 45.0),
    (-31.0, 30.0, -30.0, 45.0),
]


def inside_any(x, z, rects):
    for x0, z0, x1, z1 in rects:
        if x0 <= x <= x1 and z0 <= z <= z1:
            return True
    return False


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 1
    out_path = sys.argv[1]

    vertices = []
    vertex_index = {}

    def vertex(x, y, z):
        key = (round(x, 4), round(y, 4), round(z, 4))
        existing = vertex_index.get(key)
        if existing is not None:
            return existing
        vertices.append(key)
        vertex_index[key] = len(vertices)  # OBJ indices are 1-based.
        return len(vertices)

    faces = []

    # Ground. Winding is chosen so the face normal points at +Y; Recast decides
    # walkability from that normal, so a flipped ground quad would read as a
    # ceiling and silently vanish from the navmesh.
    steps = int(2 * HALF_EXTENT / CELL)
    for ix in range(steps):
        for iz in range(steps):
            x0 = -HALF_EXTENT + ix * CELL
            z0 = -HALF_EXTENT + iz * CELL
            x1 = x0 + CELL
            z1 = z0 + CELL
            if inside_any((x0 + x1) * 0.5, (z0 + z1) * 0.5, PITS):
                continue
            faces.append([
                vertex(x0, 0.0, z0),
                vertex(x0, 0.0, z1),
                vertex(x1, 0.0, z1),
                vertex(x1, 0.0, z0),
            ])

    # Walls, as open-bottomed boxes: the ground already covers the underside,
    # and the sides are vertical, so nothing here is walkable except the 1 m top
    # that erosion removes.
    for x0, z0, x1, z1 in WALLS:
        top = WALL_HEIGHT
        a = vertex(x0, top, z0)
        b = vertex(x0, top, z1)
        c = vertex(x1, top, z1)
        d = vertex(x1, top, z0)
        la = vertex(x0, 0.0, z0)
        lb = vertex(x0, 0.0, z1)
        lc = vertex(x1, 0.0, z1)
        ld = vertex(x1, 0.0, z0)
        faces.append([a, b, c, d])
        faces.append([la, lb, b, a])
        faces.append([lb, lc, c, b])
        faces.append([lc, ld, d, c])
        faces.append([ld, la, a, d])

    with open(out_path, "w") as stream:
        stream.write("# obstructed_field -- generated by "
                     "tools/make_obstructed_field_obj.py, do not hand edit\n")
        stream.write("# Flat %g x %g ground with %d pits and %d walls, one of\n"
                     % (2 * HALF_EXTENT, 2 * HALF_EXTENT, len(PITS), len(WALLS)))
        stream.write("# which group forms a sealed courtyard.\n")
        stream.write("o obstructed_field\n")
        for x, y, z in vertices:
            stream.write("v %g %g %g\n" % (x, y, z))
        for face in faces:
            stream.write("f %s\n" % " ".join(str(index) for index in face))
    print("wrote %s: %d vertices, %d faces" % (out_path, len(vertices), len(faces)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
